name: 📑 Feature Request
description: Suggest an idea for this project
title: "📑 Feature Request: "
labels: 
  - enhancement
  - gssoc24-ext
  - hacktoberfest
  - hacktoberfest-accepted
  - gssoc
  - gssoc24
  - gssoc-extd

body:
  - type: checkboxes
    id: checkboxes_multiple_with_required_item
    attributes:
      label: IMPORTANT TO CHECK BEFORE ISSUE
      description: You may select more than one.
      options:
        - label: You check that same issue is not present in the repository
          required: true
        - label: You have read contribution guidelines and rules
    validations:
      required: false
  - type: markdown
    attributes:
      value: Thank you for taking the time to file a Feature Request report.
  - type: textarea
    attributes:
      label: Please describe your feature request related to a problem?
      description: 'A one liner title for feature.'
  - type: textarea
    attributes:
      label: Describe your solution to problem
      description: 'A clear and concise description of what you want to happen.'
  - type: textarea
    attributes:
      label: Describe alternatives you have considered
      description: 'A clear and concise description of any alternative solutions or features you have considered.'
  - type: textarea
    attributes:
      label: Additional context
      description: 'Add any other context or screenshots about the feature request here.'
  - type: textarea
    attributes:
      label: Add Relevant Screenshot (if available)
      description: 'supporting an issue'





      











